### ISSUE TITLE
"Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)"

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-ubuntu-1604#7]
Looks like this error is rearing its ugly head again. We need to fix the automatic updates defaults fully.

See related bug in bento: https://github.com/chef/bento/issues/609

**Comment by geerlingguy** [comment]
To reproduce, use the following Vagrantfile with the current version of the `geerlingguy/ubuntu1604

**Comment by geerlingguy** [comment]
Related earlier commit (which didn't quite do the job): https://github.com/geerlingguy/packer-ubuntu-1604/commit/dac33a6d4b1a4d863c3293bf778c9ab31e67005c

**Comment by geerlingguy** [comment]
Uploading box version 1.0.3 now.

**Comment by geerlingguy** [comment]
Testing...

**Comment by geerlingguy** [comment]
I _think_ this is fixed now. Hopefully for good.

**Comment by gretel** [comment]
@geerlingguy looks like i can get rid of https://gist.github.com/gretel/34008d667a8a243a9682e5207619ad95 now. regards

**Comment by geerlingguy** [comment]
Awesome!

**Comment by Eightbiter** [comment]
Vagrant.configure(2) do |config|
  config.vm.box = "gbarbieru/xenial"

  config.vm.network "public_network" , ip: "192.168.1.111"

  config.vm.provision "shell" do |s|
    s.path = "//home/setupsc.sh"
  end

end

 this is my VAGRANTFILE, when i run vagrant up i get:

==> default: Reading package lists...
==> default: E
==> default: : 
==> default: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
==> default: E
==> default: : 
==> default: Unable to lock directory /var/lib/apt/lists/

but when i run: vagrant reload --provision it works.
Is this something that i should get used to or is there a way i can get it to work on the first initial up?

**Comment by Hashfyre** [comment]
This is still not fixed encountering this while baking Amazon Images (AMIs) with `ansible + packer`

**Comment by ForzaGreen** [comment]
I had this `Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)` with Packer. I resolved it by increasing sleep time in my shell provisionner, from 30 seconds to 80 seconds:
```json
"provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 80",
```

**Comment by jonmcclung** [comment]
I ran into this issue with a different Ubuntu VM using Vagrant, and I thought I would post my workaround here for any future Googlers:

wrap all your "apt" calls in this function:

```bash
function wait_for_apt_lock() {
    while [ "" = "" ]; do
        eval "$1" 2>/dev/null
        if [ $? -eq 0 ]; then
            break
        fi
        sleep 1
        echo "Waiting for apt lock..."
    done
}
```

Like so:

```bash
wait_for_apt_lock "apt-get update"
```

**Comment by arno01** [comment]
Rather than expecting ``rc=0`` from ``apt-get`` which may actually fail and then it will end in a dead-loop.. (rare, but possible), I'd suggest using ``while fuser -s /var/lib/dpkg/lock; do sleep 1; done; apt-get update/upgrade/...``. This will make sure you will get to run ``apt-get`` commands only when no other apt-get command is running (locking).
Of course this is not a race-proof solution, but usually it is more than enough.

**Comment by zigius** [comment]
for me the solution was simply deleting the lock before the apt-get update:

```bash
# inside a shell provisioner - 

sleep 30
sudo rm /var/lib/dpkg/lock
sudo apt-get update
sudo apt-get install -y jq

# rest of the script.....
```

**Comment by sanzenwin** [comment]
@arno01, thanks, it works
